### ISSUE TITLE
Crash regarding "Duplicate delegates" in a server replay scenario

### ISSUE THREAD

**Issue by o7q** [Sam54123/mc-world-export#15]
So far this mod has been phenomenal! It has worked in every singleplayer case nearly flawlessly. Recently I have been experimenting by trying it with server replay files.

I have encountered a crash I get pretty regularly when trying to use this mod on a server, the error I am getting is `java.lang.IllegalArgumentException: Duplicate delegates`. I am trying to figure out how it occurs. I have narrowed it down to: servers, and lobbies that have players in them. It only crashes sometimes when players are in the lobby. I am wondering if you have any ideas what this means and how it could be avoided, or even fixed? **I have provided the full crash-report below.**

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2022-12-08 12:14:23
Description: Exporting Replay

java.lang.IllegalArgumentException: Duplicate delegates
	at net.minecraft.class_4720$class_4589.<init>(class_4720.java:29)
	at net.minecraft.class_4720.method_24037(class_4720.java:15)
	at net.minecraft.class_918.method_29711(class_918.java:219)
	at net.minecraft.class_918.method_23179(class_918.java:165)
	at org.scaffoldeditor.worldexport.replay.models.ReplayItemRenderer.renderItem(ReplayItemRenderer.java:35)
	at org.scaffoldeditor.worldexport.replay.feature_adapters.HeldItemFeatureAdapter.genItemModel(HeldItemFeatureAdapter.java:139)
	at org.scaffoldeditor.worldexport.replay.feature_adapters.HeldItemFeatureAdapter.writePose(HeldItemFeatureAdapter.java:107)
	at org.scaffoldeditor.worldexport.replay.model_adapters.BipedModelAdapter.writePose(BipedModelAdapter.java:65)
	at org.scaffoldeditor.worldexport.replay.model_adapters.PlayerModelAdapter.writePose(PlayerModelAdapter.java:37)
	at org.scaffoldeditor.worldexport.replay.model_adapters.LivingModelAdapter.getPose(LivingModelAdapter.java:205)
	at org.scaffoldeditor.worldexport.replay.ReplayEntity.capture(ReplayEntity.java:142)
	at org.scaffoldeditor.worldexport.replaymod.ReplayFrameCapturer.captureEntity(ReplayFrameCapturer.java:145)
	at it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap$1.forEach(Int2ObjectLinkedOpenHashMap.java:1767)
	at com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:110)
	at org.scaffoldeditor.worldexport.replaymod.ReplayFrameCapturer.process(ReplayFrameCapturer.java:116)
	at com.replaymod.render.rendering.Pipeline.run(Pipeline.java:69)
	at com.replaymod.render.rendering.VideoRenderer.renderVideo(VideoRenderer.java:225)
	at org.scaffoldeditor.worldexport.replaymod.gui.GuiExportSettings.export(GuiExportSettings.java:77)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractGuiClickable.onClick(AbstractGuiClickable.java:71)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractGuiButton.onClick(AbstractGuiButton.java:149)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractGuiClickable.mouseClick(AbstractGuiClickable.java:53)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScreen$MinecraftGuiScreen.lambda$mouseClicked$2(AbstractGuiScreen.java:312)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$7(ComposedGuiElement.java:82)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement.forEach(AbstractComposedGuiElement.java:71)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:78)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$6(ComposedGuiElement.java:81)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement.forEach(AbstractComposedGuiElement.java:68)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:78)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$6(ComposedGuiElement.java:81)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement.forEach(AbstractComposedGuiElement.java:68)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:78)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$6(ComposedGuiElement.java:81)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement.forEach(AbstractComposedGuiElement.java:68)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:78)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$6(ComposedGuiElement.java:81)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement.forEach(AbstractComposedGuiElement.java:68)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:78)
	at com.replaymod.lib.de.johni0702.minecraft.gui.popup.AbstractGuiPopup.invokeHandlers(AbstractGuiPopup.java:172)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$6(ComposedGuiElement.java:81)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.AbstractComposedGuiElement.forEach(AbstractComposedGuiElement.java:68)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:78)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.lambda$invokeHandlers$5(ComposedGuiElement.java:74)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.forEach(ComposedGuiElement.java:42)
	at com.replaymod.lib.de.johni0702.minecraft.gui.element.ComposedGuiElement.invokeHandlers(ComposedGuiElement.java:74)
	at com.replaymod.lib.de.johni0702.minecraft.gui.container.AbstractGuiScreen$MinecraftGuiScreen.method_25402(AbstractGuiScreen.java:312)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:204)
	at net.minecraft.class_1041.method_15998(class_1041.java:315)
	at net.minecraft.class_310.method_1523(class_310.java:1204)
	at net.minecraft.class_310.method_1514(class_310.java:767)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.1
	Minecraft Version ID: 1.19.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 6701937984 bytes (6391 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2488
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2737
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 42894.02
	Virtual memory used (MB): 28122.18
	Swap memory total (MB): 10240.00
	Swap memory used (MB): 111.52
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xms8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.58.5+1.19.1
			fabric-api-base: Fabric API Base 0.4.9+e62f51a395
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f4095
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.15+d5533c0195
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f4095
			fabric-command-api-v1: Fabric Command API (v1) 1.2.9+f71b366f95
			fabric-command-api-v2: Fabric Command API (v2) 2.1.5+0c17ea9695
			fabric-commands-v0: Fabric Commands (v0) 0.2.26+df3654b395
			fabric-containers-v0: Fabric Containers (v0) 0.1.31+df3654b395
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213e95
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d2495
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4a95
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.5+a680b9b495
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f78595
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f4095
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f4095
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b395
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+1899036195
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c4395
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f4095
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f4095
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b395
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc73895
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e56895
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c695
			fabric-message-api-v1: Fabric Message API (v1) 5.0.1+4e0178f495
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc73895
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f4095
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.1+3082331495
			fabric-networking-v0: Fabric Networking (v0) 0.3.18+df3654b395
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f4095
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553a95
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.21+23c4cfef95
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f4095
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39f95
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b395
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f4095
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f4095
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b395
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f4095
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a395
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e095
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effaf95
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.10+9ff28f4095
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f4095
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a395
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c695
		fabricloader: Fabric Loader 0.14.11
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.1
		replaymod: Replay Mod 1.19.1-2.6.9
		worldexport: Replay Exporter 0.4.0
			de_javagl_obj: obj 0.3.0
			org_joml_joml: joml 1.10.2
```

**Comment by o7q** [comment]
I have done some research and it may have to do with enchanted items being in the inventory, not 100% sure though.

**Comment by o7q** [comment]
Maybe you could add a debug feature that allows you to ignore certain stored packets/entity info provided by the replay file when exporting.

**Comment by Sam54123** [comment]
Thanks for bringing that to my attention! Looking at the crash log, it definitely seems like an oversight in my code. I'll investigate it when I get the chance!

**Comment by o7q** [comment]
Awesome! Thank you.

**Comment by Sam54123** [comment]
Can you post an example `.mcpr` file that crashed?

**Comment by Sam54123** [comment]
[Fixed!](https://github.com/Sam54123/mc-world-export/releases/tag/v0.4.1)

**Comment by o7q** [comment]
Awesome! Sorry I did not see your reply in time to provide the `.mcrp` file. But it seems like you figured it already already. I will try it out soon. I will close this issue if it works.

**Comment by o7q** [comment]
I think it worked! Thank you so much for the fast response.

Also a quick note: I think you should specify which version the mod is for, I see you did it on the very first release. It might be a little confusing to newcomers.
